# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import pizarron2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFERENCIA', models.CharField(blank=True, max_length=20, null=True)),
                ('FECHACREACION', models.DateField(auto_now_add=True, verbose_name='FECHA CREACIÓN')),
                ('IMPORTEPEDIDO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMPORTE PEDIDO')),
                ('IMPORTEFACTURA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMPORTE FACTURA')),
                ('KG', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='KILOGRAMOS')),
                ('KGPCONSOLIDADO', models.SmallIntegerField(blank=True, null=True, verbose_name='% KG CONSOLIDADO')),
                ('CBMPCONSOLIDADO', models.SmallIntegerField(blank=True, null=True, verbose_name='% CBM CONSOLIDADO')),
                ('MONTOPCONSOLIDADO', models.SmallIntegerField(blank=True, null=True, verbose_name='% IMPORTE FACTURA CONSOLIDADO')),
                ('CBM', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CARGA', models.CharField(blank=True, choices=[('20DC', ' 20DC'), ('40DC', ' 40DC'), ('40HQ', ' 40HQ')], max_length=4, null=True)),
                ('ESTATUS', models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('CONCLUIDO', 'CONCLUIDO')], default='PENDIENTE', max_length=9, null=True)),
                ('ESTADO', models.CharField(blank=True, choices=[('ECP', 'ETA-CEDIS-PVTA'), ('ADUANA', 'ADUANA'), ('ARRIBADO', 'ARRIBADO'), ('PAGPED', 'PAGPED'), ('SOL', 'SOL'), ('GONDOLA', 'GONDOLA'), ('PENTACO', 'PENTACO'), ('SEMANA', 'SEMANA')], max_length=20, null=True)),
                ('MONTOFLETE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MONTO FLETE')),
                ('FECHABL', models.DateField(blank=True, null=True, verbose_name='FECHA BL')),
                ('FECHAETA', models.DateField(blank=True, null=True, verbose_name='FECHA ETA')),
                ('FECHACEDIS', models.DateField(blank=True, null=True, verbose_name='FECHA CEDIS')),
                ('FECHAPREVENTA', models.DateField(blank=True, null=True, verbose_name='FECHA PREVENTA')),
                ('FECHASEMANA', models.DateField(blank=True, null=True, verbose_name='FECHA SEMANA')),
                ('ORIGEN', models.CharField(blank=True, choices=[('NINGBO', ' NINGBO'), ('SHANGHAI', ' SHANGHAI'), ('QINGDAO', ' QINGDAO'), ('WUHU', ' WUHU'), ('CHANGZHOU', ' CHANGZHOU'), ('ARGENTINA', ' ARGENTINA'), ('BRASIL', ' BRASIL'), ('INDIA', ' INDIA'), ('TURQUIA', ' TURQUIA')], max_length=10, null=True, verbose_name='ORIGEN')),
                ('DESTINO', models.CharField(blank=True, choices=[('MANZANILLO', ' MANZANILLO'), ('LAZARO', ' LAZARO'), ('VERACRUZ', ' VERACRUZ')], max_length=10, null=True, verbose_name='DESTINO')),
                ('CONTENEDORNO', models.CharField(blank=True, max_length=20, null=True, verbose_name='NO. CONTENEDOR')),
                ('FWD', models.CharField(blank=True, choices=[('GEOCARGO', ' GEOCARGO'), ('PLUSCARGO', ' PLUSCARGO'), ('SCHNELLER', ' SCHNELLER'), ('DRAGONCARGO', ' DRAGONCARGO'), ('GLOMEX', ' GLOMEX'), ('HAMBURG', ' HAMBURG'), ('HAPAG-LLOYD', ' HAPAG-LLOYD'), ('HELLMANN', ' HELLMANN'), ('NA', ' NA')], max_length=20, null=True, verbose_name='FWD')),
                ('FACTURAFWD', models.CharField(blank=True, max_length=30, null=True, verbose_name='FACTURA FWD')),
                ('FECHAPAGOFWD', models.DateField(blank=True, null=True, verbose_name='FECHA PAGO FWD')),
                ('NUEVOS', models.TextField(blank=True, null=True)),
                ('MEJORAS', models.TextField(blank=True, null=True)),
                ('OMISIONPREVIOORIGEN', models.TextField(blank=True, null=True)),
                ('ESPECIAL', models.TextField(blank=True, null=True)),
                ('FCECP', models.DateField(blank=True, null=True)),
                ('FCADUANA', models.DateField(blank=True, null=True)),
                ('FCARRIBADO', models.DateField(blank=True, null=True)),
                ('FCPAGPED', models.DateField(blank=True, null=True)),
                ('FCSOL', models.DateField(blank=True, null=True)),
                ('FCGONDOLA', models.DateField(blank=True, null=True)),
                ('FCPENTACO', models.DateField(blank=True, null=True)),
                ('FCSEMANA', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedor',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDMOV', models.IntegerField(blank=True, null=True)),
                ('REFERENCIA', models.CharField(blank=True, max_length=20, null=True)),
                ('IMPORTEPEDIDO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMPORTE PEDIDO')),
                ('ESTAENPAGO', models.CharField(blank=True, max_length=20, null=True, verbose_name='ESTA EN PAGO')),
                ('IMPORTEFACTURA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMPORTE FACTURA')),
                ('FECHAPEDIDO', models.DateField(blank=True, null=True, verbose_name='FECHA PEDIDO')),
                ('FECHATENTENTREGA', models.DateField(blank=True, null=True, verbose_name='FECHA TENT. ENTREGA')),
                ('KG', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('CBM', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('CARGA', models.CharField(blank=True, max_length=10, null=True)),
                ('PDELCONTENEDOR', models.CharField(blank=True, max_length=20, null=True, verbose_name='% DEL CONTENEDOR')),
                ('PVALORFACTURA', models.CharField(blank=True, max_length=20, null=True, verbose_name='% VALOR FACTURA')),
                ('PESO', models.CharField(blank=True, max_length=20, null=True, verbose_name='% PESO')),
                ('PCBM', models.CharField(blank=True, max_length=20, null=True, verbose_name='% CBM')),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=pizarron2.models.Contenedor, related_name='contenedorr', to='pizarron2.Contenedor')),
            ],
            options={
                'verbose_name': 'Contnedor',
                'verbose_name_plural': 'Contenedor',
            },
        ),
    ]
