# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarron2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='REFERENCIA',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
