# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarron2', '0002_auto_20171114_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='IMPORTEFACTURA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IMPORTE FACTURA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referencia',
            name='IMPORTEPEDIDO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IMPORTE PEDIDO'),
            preserve_default=False,
        ),
    ]
