# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarron2', '0004_auto_20171211_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='FCENRUTA',
            field=models.DateField(blank=True, null=True),
        ),
    ]
