# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarron2', '0005_contenedor_fcenruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='RALFECHABL',
            field=models.DateField(blank=True, null=True, verbose_name=' REAL FECHA BL'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='RALFECHAETA',
            field=models.DateField(blank=True, null=True, verbose_name=' REAL FECHA ETA'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='ESTADO',
            field=models.CharField(blank=True, choices=[('ECP', 'ETA-CEDIS-PVTA'), ('ADUANA', 'ADUANA'), ('ARRIBADO', 'ARRIBADO'), ('PAGPED', 'PAGPED'), ('SOL', 'SOL'), ('GONDOLA', 'GONDOLA'), ('ENRUTA', 'ENRUTA'), ('PENTACO', 'PENTACO'), ('SEMANA', 'SEMANA')], max_length=20, null=True),
        ),
    ]
